version: '3'

services:
  dash:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['python', 'app.py']
    ports:
      - '8050:8050'
    environment:
      - PYTHONPATH=/app
      - DASH_DEBUG=true
    volumes:
      - .:/app
